#Get USER
GET http://localhost:5000/api/user/get

### Add new User 
POST http://localhost:5000/api/user/new-user
Content-Type: application/json

{
    "name": {
      "first": "Test",
      "mid": "Test",
      "last": "Test" 
    },
    "designation": "Programmer",  
    "status": "Job Order",
    "office": "5ec23aafe783e810cc209a98",
    "role": "5ec4e549e783e810cc209ad6"
}
/**
Remarks:
"role": "5ec4e549e783e810cc209ad6" is constant
-----
Create a temp add user api to not generate new DOH ID
with this api:
/api/user/temp/new-user 
Output:

  "status": true,
  "user": {
    "_id": "620f0aca93d6da33e001892a",
    "username": "test.test",
    "password": "$2a$10$FYX13f6yLEUOZpHMmp6yLuurI5MZocbSXICEsw4LLEe.ehhodOfdS",
    "name": {
      "first": "Test",
      "mid": "Test",
      "last": "Test"
    },
    "designation": "Programmer",
    "status": "Job Order",
    "office": "5ec23aafe783e810cc209a98",
    "role": "5ec4e549e783e810cc209ad6",
    "userID": "DOH13U-0222-000",
    "__v": 0
  }
}
*/

### Get Offices
# if office is not in selection
GET http://localhost:5000/api/office/get

###
POST http://localhost:5000/api/office/new
Content-Type: application/json

{
    "division": "MSD",
    "section": "ACCOUNTING",
    "code": "MSD",
    "officeID": "DOH13O-2005-000"
}

### Get Device
GET http://localhost:5000/api/device/get

### get
GET http:/localhost:5000/api/jobOrderRequest/get
###
#remakrs must have temp model for eportal
###tested
POST http://localhost:5000/api/jobOrderRequest/new
Content-Type: application/json

{
  "jobOrderRequest": {
    "supervisor": {
        "seen": null
    },
    "technician": {
        "seen": null,
        "dateAction": {
            "$date": ""
        },
        "actionDetails": {
            "scopeOfWork": "",
            "checkUpResult": "",
            "recommendations": "NA",
            "specifications": "NA"
        }
    },
    "status": "done",
    "jobOrderRequestID": "",
    "requestingPersonnel": {
        "name": "PANGO, SARAH SAUSA",
        "designation": "Administrative Officer IV",
        "divSec": "MSD - GENERAL SERVICES"
    },
    "device": "5f55e8aec546ba3794283b09",
    "natureOfComplaint": "TEST"
  }
}
